import streamlit as st
import PyPDF2
import hashlib
import datetime
import io
import re
from groq import Groq
from gtts import gTTS
from docx import Document

import os
client = Groq(api_key=os.environ.get("GROQ_API_KEY"))


def generate_content(prompt):
    response = client.chat.completions.create(
        model="openai/gpt-oss-20b",
        messages=[{"role": "user", "content": prompt}]
    )
    return response.choices[0].message.content


# ---------------- VOICE FEATURE: Text-to-Speech ----------------
LANG_CODES = {
    "Tamil": "ta", "Hindi": "hi", "Telugu": "te", "Kannada": "kn",
    "Malayalam": "ml", "English": "en", "French": "fr",
}


def text_to_speech(text, lang_code):
    """Converts text into spoken audio (mp3) for the given language."""
    safe_text = text[:2000]  # keep it quick for demo purposes
    tts = gTTS(text=safe_text, lang=lang_code)
    audio_buffer = io.BytesIO()
    tts.write_to_fp(audio_buffer)
    audio_buffer.seek(0)
    return audio_buffer


# ---------------- CYBERSECURITY: Document Integrity Check ----------------
def get_file_hash(file_bytes):
    """SHA-256 hash — proves the document has not been tampered with."""
    return hashlib.sha256(file_bytes).hexdigest()


# ---------------- SECURITY SCORE: PII + RISK DETECTION ----------------
def security_score(text):
    """Detects common PII patterns and calculates a simple risk score."""
    findings = []

    patterns = {
        "Email Address": r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b",
        "Phone Number": r"(?<!\d)(?:\+?\d[\d\s().-]{8,}\d)(?!\d)",
        "Credit/Debit Card": r"\b(?:\d[ -]*?){13,19}\b",
        "Aadhaar-like Number": r"(?<!\d)\d{4}\s?\d{4}\s?\d{4}(?!\d)",
        "IP Address": r"\b(?:\d{1,3}\.){3}\d{1,3}\b",
        "Date of Birth": r"\b(?:DOB|Date of Birth|Birth Date)\s*[:\-]?\s*\d{1,2}[/-]\d{1,2}[/-]\d{2,4}\b",
    }

    for label, pattern in patterns.items():
        matches = re.findall(pattern, text, flags=re.IGNORECASE)
        if matches:
            findings.append((label, len(matches)))

    # Avoid counting Aadhaar-like matches twice as generic phone/card numbers.
    labels = {x[0] for x in findings}
    if "Aadhaar-like Number" in labels:
        findings = [(label, count) for label, count in findings
                    if label not in {"Phone Number", "Credit/Debit Card"}]

    if not findings:
        score = 100
        risk = "LOW"
    else:
        total = sum(count for _, count in findings)
        score = max(0, 100 - min(90, total * 15))
        if score >= 70:
            risk = "LOW"
        elif score >= 40:
            risk = "MEDIUM"
        else:
            risk = "HIGH"

    return score, risk, findings


# ---------------- BLOCKCHAIN-STYLE AUDIT TRAIL ----------------
if "audit_chain" not in st.session_state:
    st.session_state.audit_chain = []


def add_block(action, output_text):
    previous_hash = st.session_state.audit_chain[-1]["block_hash"] if st.session_state.audit_chain else "0" * 64
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    output_hash = hashlib.sha256(output_text.encode()).hexdigest()

    block_content = f"{previous_hash}{timestamp}{action}{output_hash}"
    block_hash = hashlib.sha256(block_content.encode()).hexdigest()

    block = {
        "index": len(st.session_state.audit_chain) + 1,
        "timestamp": timestamp,
        "action": action,
        "output_hash": output_hash[:16] + "...",
        "previous_hash": previous_hash[:16] + "...",
        "block_hash": block_hash,
    }
    st.session_state.audit_chain.append(block)


def verify_chain():
    """Re-walks the chain and checks every link — detects tampering."""
    chain = st.session_state.audit_chain
    for i in range(1, len(chain)):
        if chain[i]["previous_hash"] != chain[i - 1]["block_hash"][:16] + "...":
            return False
    return True


# ---------------- HISTORY (viewable & deletable) ----------------
if "history" not in st.session_state:
    st.session_state.history = []


def add_history(filename, action, output_text):
    st.session_state.history.append({
        "id": len(st.session_state.history) + 1 if not st.session_state.history
              else st.session_state.history[-1]["id"] + 1,
        "timestamp": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "filename": filename,
        "action": action,
        "output": output_text,
    })


# ---------------- DOWNLOAD ALL RESULTS: WORD ----------------
def create_word_document(history, filename="ContentForge_All_Results.docx"):
    doc = Document()
    doc.add_heading("ContentForge - AI Content Transformation Results", 0)
    doc.add_paragraph(
        "Generated by ContentForge. This document contains all transformation "
        "results recorded in the current session."
    )
    doc.add_paragraph(
        f"Generated on: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    )

    for i, item in enumerate(history, start=1):
        doc.add_heading(f"{i}. {item['action']}", level=1)
        doc.add_paragraph(f"File: {item['filename']}")
        doc.add_paragraph(f"Time: {item['timestamp']}")
        doc.add_paragraph(item["output"])

    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer


# ---------------- UI ----------------
st.set_page_config(page_title="ContentForge - AI Content Transformer", layout="wide")

st.title("🔐 ContentForge - AI Content Transformer")
st.write("**PS 26154** - Gen AI Platform for Automated Content Transformation")
st.caption("Secured with SHA-256 document integrity checks and a blockchain-style tamper-proof audit trail.")

uploaded_file = st.file_uploader("Upload a PDF", type="pdf")

if uploaded_file:
    file_bytes = uploaded_file.getvalue()
    doc_hash = get_file_hash(file_bytes)
    with st.expander("🛡️ Document Integrity (Cybersecurity Layer)"):
        st.write("SHA-256 Hash of uploaded document:")
        st.code(doc_hash)
        st.caption("This fingerprint proves the file has not been altered since upload.")

    # ---- Security Score Dashboard ----
    reader_preview = PyPDF2.PdfReader(io.BytesIO(file_bytes))
    preview_text = ""
    for page in reader_preview.pages:
        preview_text += page.extract_text() or ""

    score, risk, findings = security_score(preview_text)

    st.subheader("🛡️ Security Score Dashboard")
    score_col, risk_col, pii_col = st.columns(3)
    with score_col:
        st.metric("Security Score", f"{score}/100")
    with risk_col:
        st.metric("Risk Level", risk)
    with pii_col:
        st.metric("PII Categories Detected", len(findings))

    if findings:
        st.warning("⚠️ Potential PII detected in the uploaded document.")
        for label, count in findings:
            st.write(f"- **{label}:** {count} occurrence(s)")
    else:
        st.success("✅ No common PII patterns detected.")

    st.progress(score / 100)
    st.caption(
        "Score is a rule-based screening indicator, not a guarantee that the "
        "document contains no sensitive information."
    )

st.write("Choose transformation(s):")
col1, col2 = st.columns(2)
with col1:
    summarize = st.checkbox("Summarize")
    translate = st.checkbox("🌐 Translate")

    # Language dropdown appears only when Translate is checked
    selected_languages = []
    if translate:
        selected_languages = st.multiselect(
            "Select language(s) to translate into:",
            ["Tamil", "Hindi", "Telugu", "Kannada", "Malayalam", "English", "French"],
            default=["Tamil"],
        )

    bullets = st.checkbox("Convert to Bullet Points")
    entities = st.checkbox("🔍 Extract Key Entities (Names/Dates/Places)")
with col2:
    risk_flag = st.checkbox("⚠️ Risk & Sensitive Content Flagger")
    action_items = st.checkbox("✅ Extract Action Items")
    simplify = st.checkbox("🧒 Simplify (Explain Like I'm 5)")
    faqs = st.checkbox("❓ Generate FAQs")

if uploaded_file and st.button("Transform"):
    reader = PyPDF2.PdfReader(uploaded_file)
    text = ""
    for page in reader.pages:
        text += page.extract_text() or ""

    # Save security results into history too
    score, risk, findings = security_score(text)
    security_report = (
        f"Security Score: {score}/100\n"
        f"Risk Level: {risk}\n"
        f"PII Categories Detected: {len(findings)}\n"
    )
    if findings:
        security_report += "\nDetected PII patterns:\n"
        for label, count in findings:
            security_report += f"- {label}: {count} occurrence(s)\n"
    else:
        security_report += "\nNo common PII patterns detected."

    add_history(uploaded_file.name, "Security Score Dashboard", security_report)

    with st.spinner("AI is processing..."):
        if summarize:
            output = generate_content(f"Summarize this document in 150 words:\n{text}")
            st.subheader("Summary:")
            st.write(output)
            add_block("Summarize", output)
            add_history(uploaded_file.name, "Summarize", output)

        if translate:
            if not selected_languages:
                st.warning("Please select at least one language to translate into.")
            for lang in selected_languages:
                output = generate_content(f"Translate this document into {lang}:\n{text}")
                st.subheader(f"🌐 {lang} Translation:")
                st.write(output)
                add_block(f"Translate to {lang}", output)
                add_history(uploaded_file.name, f"Translate to {lang}", output)

                # 🔊 Voice playback of the translated text
                lang_code = LANG_CODES.get(lang, "en")
                try:
                    with st.spinner(f"Generating {lang} voice..."):
                        audio_buffer = text_to_speech(output, lang_code)
                    st.audio(audio_buffer, format="audio/mp3")
                except Exception as e:
                    st.warning(f"Voice generation failed for {lang}: {e}")

        if bullets:
            output = generate_content(f"Convert this into clear bullet points:\n{text}")
            st.subheader("Bullet Points:")
            st.write(output)
            add_block("Convert to Bullet Points", output)
            add_history(uploaded_file.name, "Convert to Bullet Points", output)

        if entities:
            output = generate_content(
                f"Extract all key entities from this document — names of people, "
                f"organizations, dates, and locations. Present as a clean list grouped "
                f"by category:\n{text}"
            )
            st.subheader("🔍 Key Entities:")
            st.write(output)
            add_block("Extract Key Entities", output)
            add_history(uploaded_file.name, "Extract Key Entities", output)

        if risk_flag:
            output = generate_content(
                f"Review this document and flag any sensitive, confidential, or risky "
                f"information (e.g. personal data, financial details, security-related "
                f"content). List each flagged item with a short reason. If nothing risky "
                f"is found, say so clearly:\n{text}"
            )
            st.subheader("⚠️ Risk & Sensitive Content Flags:")
            st.write(output)
            add_block("Risk Flagging", output)
            add_history(uploaded_file.name, "Risk Flagging", output)

        if action_items:
            output = generate_content(
                f"Extract all action items, tasks, or to-dos mentioned in this document. "
                f"Present as a numbered checklist. If none exist, say so:\n{text}"
            )
            st.subheader("✅ Action Items:")
            st.write(output)
            add_block("Extract Action Items", output)
            add_history(uploaded_file.name, "Extract Action Items", output)

        if simplify:
            output = generate_content(
                f"Explain the content of this document in very simple language, as if "
                f"explaining to a 10-year-old. Avoid jargon:\n{text}"
            )
            st.subheader("🧒 Simplified Explanation:")
            st.write(output)
            add_block("Simplify (ELI5)", output)
            add_history(uploaded_file.name, "Simplify (ELI5)", output)

        if faqs:
            output = generate_content(
                f"Generate 5 frequently asked questions (with short answers) based on "
                f"this document:\n{text}"
            )
            st.subheader("❓ Generated FAQs:")
            st.write(output)
            add_block("Generate FAQs", output)
            add_history(uploaded_file.name, "Generate FAQs", output)

    st.success("✅ Transformation complete and recorded in the secure audit trail below.")

# ---------------- DOWNLOAD ALL RESULTS ----------------
if st.session_state.history:
    st.divider()
    st.subheader("📥 Download All Results")

    word_file = create_word_document(st.session_state.history)

    st.download_button(
        label="📄 Download All Results as Word Document",
        data=word_file,
        file_name="ContentForge_All_Results.docx",
        mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    )

# ---------------- AUDIT TRAIL DISPLAY ----------------
if st.session_state.audit_chain:
    st.divider()
    st.subheader("⛓️ Blockchain-Style Audit Trail")
    st.caption("Every transformation is cryptographically linked to the one before it — tampering with any past entry breaks the chain.")

    for block in reversed(st.session_state.audit_chain):
        st.write(
            f"**Block #{block['index']}** | {block['timestamp']} | Action: `{block['action']}`"
        )
        st.code(f"Output Hash: {block['output_hash']}\nLinked to Previous Block: {block['previous_hash']}")

    if verify_chain():
        st.success("🔒 Chain Verified: No tampering detected.")
    else:
        st.error("⚠️ Chain Integrity Broken: Tampering detected!")

# ---------------- HISTORY DISPLAY (view & delete) ----------------
if st.session_state.history:
    st.divider()
    header_col, clear_col = st.columns([4, 1])
    with header_col:
        st.subheader("📜 History")
        st.caption("View your past transformations. Delete any entry you no longer need.")
    with clear_col:
        if st.button("🗑️ Clear All History"):
            st.session_state.history = []
            st.rerun()

    for item in reversed(st.session_state.history):
        with st.expander(f"📄 {item['filename']} — {item['action']} — {item['timestamp']}"):
            st.write(item["output"])
            if st.button("🗑️ Delete this entry", key=f"del_{item['id']}"):
                st.session_state.history = [
                    h for h in st.session_state.history if h["id"] != item["id"]
                ]
                st.rerun()
else:
    st.divider()
    st.caption("📜 No history yet — your transformations will appear here.")
